### ISSUE TITLE
Make clear in the interface the FSFE Free Choices

### ISSUE THREAD

**Issue by ghost** [contributoragreements/ca-cla-chooser#1]
Like green or some other color to show FREE, like old CC license choosers before.

**Comment by mcjsca** [comment]
clarification needed: I guess that is option 1 here?

<img width="989" alt="Screen Shot 2019-04-16 at 10 41 30 PM" src="https://user-images.githubusercontent.com/39067944/56242539-cfda5a80-6098-11e9-9895-d21a92ab656c.png">

**Comment by step21** [comment]
In this example, choosing FSFE in the beginning, it does not even show the option, just states that FSFE implies exclusive (inbound) license. For the outbound option people are free to choose.

**Comment by step21** [comment]
Closing, as it is not clear what should be highlighted. In the beginning the FSFE choice is green and later the FSFE choices such as the inbound licenses are not choosable.
