### ISSUE TITLE
Show definitions of “Legal Entity” and “Affiliate” only if the Patent Pledge option was used

### ISSUE THREAD

**Issue by silverhook** [contributoragreements/ca-cla-chooser#11]
When you generate a Custom CLA, the definitions of “Legal Entity” and “Affiliate” show up even if they are not used in the text later.

These definitions are part of the Patent Pledge option, but show up also if you choose the Patent License.

This was already fixed for the FLA version, so it might make sense to look at the code that fixed that and apply the logic instead to Patent License vs Patent Pledge.

**Comment by step21** [comment]
Should be fixed with 404c7c95f2330a71a7daab8225e2aebb65573dcc (not live yet as of this writing)

**Comment by silverhook** [comment]
@step21, do let me know when it is live. I can currently still replicate this issue.

**Comment by step21** [comment]
Try it now. Sorry for the delay. Btw, I added a neat little feature that gives latest version as short git hash, just to be sure what is running. It could be fooled probably as it uses a separate file that is updated on git pull by a post merge hook, but for knowing what version is live it should be fine.

**Comment by silverhook** [comment]
Seems to work now, thanks :+1:
