### ISSUE TITLE
PDF contains garbled characters

### ISSUE THREAD

**Issue by silverhook** [contributoragreements/ca-cla-chooser#12]
The resulting PDF includes garbled characters – I suspect there is an issue with Unicode, as all of these seem to be punctuation characters.

It seems to be OK in HTML version though.

example (see in bold):

> If You are an employee and have created the Contribution as part of your employment, You
need to have Your employer approve this Agreement or sign the Entity version of this document.
If You do not own the Copyright in the entire work of authorship, any other author of the
Contribution should also sign this **â€“** in any event, please contact Us at ____________________

There are even more if you choose the FLA option.

**Comment by step21** [comment]
Seems like incomplete or non-existent unicode handling in pdf generator. Maybe just switch to browser based pdf-generation instead.

**Comment by silverhook** [comment]
Sounds like an OK solution to me.

In the modern age, I would almost consider offering MarkDown more important – see https://github.com/contributoragreements/ca-cla-chooser/issues/5

**Comment by step21** [comment]
Or update the html2pdf thing and hope that fixes it. Personally, I disagree on markdown. While I personally like it in some documents, it's only useful in lieu of proper styling and to convert to pdf/html imo. (and the idea is that you can sign the pdf in some way, which does not work with markdown)
But apart from that, I would happily integrate it if there is an easy way. Do you know of a js library for it?

**Comment by silverhook** [comment]
The use case I have in mind re MarkDown is that then it could be easily integrated into projects’ repositories – either as a text in the repository itself or in a Gist and then used by tools like [CLA Assistant](https://cla-assistant.io/) or CLA Hub.

**Comment by step21** [comment]
Upgrading heroku stack and setting encoding seems to have fixed it. (please test) Ideally, use in-browser solution in the future but this was quicker for now.

**Comment by silverhook** [comment]
LGTM, thanks :+1:
