### ISSUE TITLE
Dead link on Governance page

### ISSUE THREAD

**Issue by silverhook** [contributoragreements/ca-cla-chooser#15]
On the [Governance](http://contributoragreements.org/governance.html) page there is a link that points to:
http://contributoragreements.org/wordpress/discuss-develop/
…but ultimately leads to nowhere (404 error)

We should fix this :)

**Comment by step21** [comment]
I think that would have to be removed as that was only active at the time.

**Comment by step21** [comment]
Fixed in db with linking to legal section. (As the site originally used for public comments is not available anymore)
