### ISSUE TITLE
URL to GitHub repository on main page

### ISSUE THREAD

**Issue by silverhook** [contributoragreements/ca-cla-chooser#16]
Currently there is no link to this GitHub repository on the main page/chooser.

It would IMHO make sense to mention it in the FAQ.

**Comment by step21** [comment]
Agreed. We are in this the process of updateing things.

**Comment by step21** [comment]
It is not mentioned under faq under 'I like the project, how can I help'. Let me know if you think it should get another mention elsewhere.
