### ISSUE TITLE
service.fabricatorz repo useless due to submodules

### ISSUE THREAD

**Issue by step21** [contributoragreements/ca-cla-chooser#26]
https://github.com/contributoragreements/service.fabricatorz.com is basically empty, as it only links to subrepos which no longer exist. Should either relink or delete.

**Comment by step21** [comment]
made first PR here https://github.com/contributoragreements/service.fabricatorz.com/pull/1
Or alternatively someone could give me access to the services repo directly.

**Comment by silverhook** [comment]
Just merged. Thank you. Anything else that needs doing here?

**Comment by step21** [comment]
All these links should be fixed to point to copies in this organization or should be replaced by the actual code.
I think I put some of these already on this organization or my personal account, not sure if all. (and I just checked and it seems my PR didn't fix it. submodules are weird sometimes)

**Comment by silverhook** [comment]
If there is anything specific I can help with, let me know. My coding skills are (very) limited, and I never tackled JS either.

If you have PRs to merge, I’m more than happy to oblige :)

**Comment by step21** [comment]
Can you do a bit of git? The idea is basically to remove the submodule link to non-existing fabricatorz repository, then make a new one to a repo under contributoragreements organization. Some of those repos also would have to be created first. If you could do the submodules, I could push the source for those mini services from the server to a new repo, then you could link them.

**Comment by silverhook** [comment]
I can do a _bit_ of git and submodules are a thing I know I don’t grasp well enough to mess with right now (yet).

I updated the team permissions for repos, so I think you should have appropriate access now.

**Comment by step21** [comment]
ok, thanks. Everybody knows _a bit_ of git ;)

**Comment by step21** [comment]
Thanks for updating permissions. I fixed them now. Probably not all of them are needed anymore, but good to have them here and not only on the server.
