### ISSUE TITLE
Entity version missing in FLA

### ISSUE THREAD

**Issue by silverhook** [contributoragreements/ca-cla-chooser#27]
When generating the FLA, it only creates an Individual version, but not an Entity version.

Having an entity version also for the FLA would be preferable.

As an alternative, we might think about whether it makes sense to update the templates to cover both the individual contributor and entity version in the same text (what do you think @catharinamaracke ?) – might be tricky or actually prove to not be a good idea though.

**Comment by step21** [comment]
As far as I understand this was deliberately taken out?

**Comment by step21** [comment]
Also best to write Catharina a mail, not sure if she gets Github emails.

**Comment by silverhook** [comment]
I think it was more the fact that we simply did get around to it. It has been requested by e-mail and in person enough times that we should have an Entity version for the FLA anyway.

**Comment by step21** [comment]
Ah ok, thanks for the info. The template as such is basically already unified now. Things are taken out/added to get each version. Not sure atm how much work it would be for FLA, depends on how much would have to change. Just things that in the other CLA or more?

**Comment by silverhook** [comment]
I think the goal would remain that the FLA and the other CLA templates would be very tightly intertwined. I.e. if you leave all options as defaults, you should obtain a CLA text which is identical to the FLA only without its preamble.

We made extra effort for this to be the case now, so I think we would continue to make the effort for this to continue in the future.

**Comment by step21** [comment]
Ok, I think we are mixing some stuff up here.
* one thing - entity for FLA, sure
* other thing - all CLA options as default results in same as FLA minus preamble
* last thing - as opposed to in beginning, agreement template is one file for all versions.
For all selections, the default selection seems to be the same as implied or selected by default for fla. (though I did not check text or code for this, just options chosen)
Adding entity version does not change that, no effort needed to keep it that way.

**Comment by silverhook** [comment]
Just had a call with @catharinamaracke and we agreed that we should just generate the Entity version from the templates as they are for the FLA as well. We both recall that the fact it does not exist is a bug and that the templates should already be written in a way that this should be done easily.

As for my note about potentially rewriting the FLA/CLA templates so there would be no need for two documents, we might look into that next year during our 2021 revision of the FLA and CLA templates, but is outside the scope of this ticket.

Does that make sense and helps you in any way to enable the Entity FLA?

**Comment by step21** [comment]
having generated 2 different examples and checking the code - individual vs entity only still matters in the name/subitle or if patent pledge, right? So in case of FLA, only the subtitle name would change, correct?

**Comment by step21** [comment]
I thought there would have to be more changes, but apparently not...

**Comment by step21** [comment]
Should be fixed in #31

**Comment by step21** [comment]
Right now, the fla-entity is different in name only. Entity defintions are only included for patent pledge, so not included for FLA which does not have that, is that ok?

 ```
$('#review-text-fla #tmp-entity-definitions').hide();
            $('#review-text-fla-entity #tmp-entity-definitions').hide();
            if ( $( "#patent-type" ).val() == 'Patent-Pledge' ) {
                $('#review-text .tmp-entity-definitions').show();
                $('#review-text-entity .tmp-entity-definitions').show();
            }
            else {
                $('#review-text .tmp-entity-definitions').hide(); 
                $('#review-text-entity .tmp-entity-definitions').hide();
```

**Comment by silverhook** [comment]
> Right now, the fla-entity is different in name only. Entity defintions are only included for patent pledge, so not included for FLA which does not have that, is that ok?

Sounds about right, yes. 

I diffed the MarkDown versions of the current FLA and the default entity CLA and it looks OK to me.

**Comment by step21** [comment]
Ok cool. (the entity version added a lot of lines still, because two seperate texts are produced and I wanted to keep the way things are produced)

**Comment by silverhook** [comment]
If you have an idea how to simplify these things, do let me know. If the diff is not really big, we should be able to simplify as much as possible.

**Comment by step21** [comment]
Merged in #31. Please test if you like. Many repetitive things could be moved to functions or similar... but didn't want to do it as part of this feature.

**Comment by silverhook** [comment]
I apologise for the late reply. Should this already work on the live instance of the chooser already?

**Comment by silverhook** [comment]
I just tried it and apart from the _name_, I don’t even see any difference in the generated Individual vs Entity version even for a non-FLA choices.

Compare e.g.:
https://contributoragreements.org/ca-cla-chooser/?beneficiary-name=bla&project-name=&project-website=&project-email=&process-url=&project-jurisdiction=&agreement-exclusivity=exclusive&fsfe-compliance=&fsfe-fla=&outbound-option=fsfe&outboundlist=&outboundlist-custom=&medialist=____________________&patent-option=Traditional&your-date=&your-name=&your-title=&your-address=&your-patents=&pos=apply&action=

**Comment by step21** [comment]
> I just tried it and apart from the _name_, I don’t even see any difference in the generated Individual vs Entity version even for a non-FLA choices.
> 
> Compare e.g.:
> https://contributoragreements.org/ca-cla-chooser/?beneficiary-name=bla&project-name=&project-website=&project-email=&process-url=&project-jurisdiction=&agreement-exclusivity=exclusive&fsfe-compliance=&fsfe-fla=&outbound-option=fsfe&outboundlist=&outboundlist-custom=&medialist=____________________&patent-option=Traditional&your-date=&your-name=&your-title=&your-address=&your-patents=&pos=apply&action=

As you can see from my comments above, that is apparently how it is supposed to be. Apart from name/subtitle and patent-pledge if chosen, there is no discernable difference. That is why I asked in above comment if that is correct. But I can only assume it must be, so unless you have different info or a future legal update concludes otherwise, this is how it is supposed to be.

**Comment by silverhook** [comment]
Seems this popped up again – see #39 and #41

**Comment by silverhook** [comment]
Re-closing in favour of https://github.com/contributoragreements/ca-cla-chooser/issues/45
