### ISSUE TITLE
generate pdf in browser

### ISSUE THREAD

**Issue by step21** [contributoragreements/ca-cla-chooser#28]
after call with @catharinamaracke 

* will lessen dependency on server
* less data privacy stuff to worry about

**Comment by step21** [comment]
WIP in # 34

**Comment by step21** [comment]
@silverhook @catharinamaracke I suggest disabling the PDF option for now. As Till suggested via email, having the html / markdown correct is more important. I took another look yesterday to find out why the other versions and pdf differ, but couldn't figure it out yet tbh. The idea would be to then fix other stuff first and clean up the code, which should make fixing this easier later.

**Comment by silverhook** [comment]
That sounds good to me, yes.

**Comment by catharinamaracke** [comment]
Hi Florian,

Many thanks - and yes, I agree as well. I was hoping that Jon or someone from his team can help fix some of the details … :-)

Thanks

Catharina

**Comment by step21** [comment]
Ok, done: https://github.com/contributoragreements/ca-cla-chooser/pull/57

**Comment by catharinamaracke** [comment]
Great, what are the relevant issue links?

Jon

**Comment by step21** [comment]
* One is this one - to fix issues with SSL and the htmltopdf php code, it would be better if it would just be generated in-browser. This works in principle and is in this PR - https://github.com/contributoragreements/ca-cla-chooser/pull/51 - but it seems that somehow it does not get passed the right text, which then means the wrong text is put into a pdf. Issue: https://github.com/contributoragreements/ca-cla-chooser/issues/28
* Apart from that, most important is probably that the url to re-generate an agreement was reported to be broken. https://github.com/contributoragreements/ca-cla-chooser/issues/14 If I remember correctly, it seemed that after adding the FLA etc, the url generating part was not propely updated. At the time, I started working on a fix here, but this is incomplete iirc https://github.com/contributoragreements/ca-cla-chooser/pull/50
* The url shortener does not work. Originally I thought maybe this was just the wrong url, but there is more wrong and comments in the code suggest it wasn't working after a move or similar. The php on the server has `Allow-cross-origin: *` but this might not be sufficient, as the browser (or at least my browser) shows requests as blocked. The log file also has errors like `[22-Oct-2014 02:44:31 America/New_York] Could not parse the ini file: db/links.ini` so there might be more issues than just cross origin. https://github.com/contributoragreements/ca-cla-chooser/issues/44
* Lastly, any help with re-factoring or otherwise making things more maintainable would also be greatly appreciated. Ideas: check if some parts of nuke/show/etc to generate agreement can be grouped in a function or similar, or be labeled more appropriately. Or f.e. we currently generate a separate modal for each result, but they are never shown at the same time. Maybe this could be a single modal, that just gets updated with text on opening it.

Also, please make a PR and allow for 1-2 days for comments before merging because merging to master will deploy automatically and it would be good to review just in case. This can also be used for your own testing, as I added a preview option that is generated for each PR. It will not help with cross-origin problems or similar things, but for everything else it is quite nice.

**Comment by step21** [comment]
As a separate 'out there' issue - if you know a good resource or person to learn or ask about adding support to automatically test the end result, i.e. if headings have proper numbering or patent pledge is there when it shouldn't (using selenium or playwright for example) any pointers would also be appreciated.

**Comment by step21** [comment]
For now, postponed as it's probably not that necessary and we have markdown now instead. If desired, it's easy to add it based on the draft PR, would mostly need style changes to make it look ok.
