### ISSUE TITLE
Make clear FSFE option vs custom option

### ISSUE THREAD

**Issue by rejon** [contributoragreements/ca-cla-chooser#3]
Basic buttons and color are there, but functionality needs testing.

**Comment by danielriesner** [comment]
Please check if my solution resolves this issue: https://contributoragreements.github.io/ca-cla-chooser/

**Comment by silverhook** [comment]
This can be closed now

**Comment by silverhook** [comment]
This seems done. Please close.

**Comment by mcjsca** [comment]
looks also good to me:
<img width="834" alt="Screen Shot 2019-04-16 at 10 35 51 PM" src="https://user-images.githubusercontent.com/39067944/56242196-05cb0f00-6098-11e9-8a4a-d2cd062c5b87.png">
