### ISSUE TITLE
cleanup text comments

### ISSUE THREAD

**Issue by step21** [contributoragreements/ca-cla-chooser#30]

**Comment by step21** [comment]
There are a lot of comments in the code, which either only comment old code or are probably more like ancient artifacts right now. I'd like to get rid of those, but that ofc also has the potential to break more things. :)

**Comment by silverhook** [comment]
That makes a lot of sense. For any comments that are not yours, it seems we are in touch with previous maintainers, so asking them for comments and aid could help.

**Comment by step21** [comment]
Inline comments were cleaned up as part of this PR https://github.com/contributoragreements/ca-cla-chooser/pull/73
Additionally, the README was updated and functions in the main js file were documented better.
