### ISSUE TITLE
No markdown generated for entity version of the FLA

### ISSUE THREAD

**Issue by adriaandegroot** [contributoragreements/ca-cla-chooser#39]
Following https://contributoragreements.org/ca-cla-chooser/?beneficiary-name=KDE+e.V.&project-name=KDE&project-website=ev.kde.org&project-email=kde-ev-board%40kde.org&process-url=https%3A%2F%2Fev.kde.org%2Frules%2Ffla%2F&project-jurisdiction=Germany&agreement-exclusivity=exclusive&fsfe-compliance=&fsfe-fla=&outbound-option=fsfe&outboundlist=&outboundlist-custom=&medialist=%5C_%5C_%5C_%5C_%5C_%5C_%5C_%5C_%5C_%5C_%5C_%5C_%5C_%5C_%5C_%5C_%5C_%5C_%5C_%5C_&patent-option=Traditional&your-date=&your-name=&your-title=&your-address=&your-patents=&pos=apply&action=](https://contributoragreements.org/ca-cla-chooser/?beneficiary-name=KDE+e.V.&project-name=KDE&project-website=ev.kde.org&project-email=kde-ev-board%40kde.org&process-url=https%3A%2F%2Fev.kde.org%2Frules%2Ffla%2F&project-jurisdiction=Germany&agreement-exclusivity=exclusive&fsfe-compliance=&fsfe-fla=&outbound-option=fsfe&outboundlist=&outboundlist-custom=&medialist=____________________&patent-option=Traditional&your-date=&your-name=&your-title=&your-address=&your-patents=&pos=apply&action= which comes out of the chooser, you end up on the final page where the "entity" agreement's *MKDN* button pops up an empty window.

The "entity" *HTML* and *PDF* buttons do produce output. The "individual" buttons all three produce output.

**Comment by adriaandegroot** [comment]
This isn't related, I don't think (at least, not to the latest stages of that issue, where it's more about the text than not having an Entity-FLA at all):

- follow that link; you end up on the "you are done" page
- next to "Fiduciary Contributor License Agreement", click the *HTML* button. Notice a new window / pop-up thingy appears, containing HTML code. Close it. Click the *MKDN* button. Notice a new window appears, containing Markdown code. Close it.
- next to "Entity Fiduciary Contributor License Agreement", click the *HTML* button. Notice a new window appears, containing HTML code. Close it. Click the *MKDN* button. The new window appears, but is totally blank. There is no text to select or copy.

**Comment by step21** [comment]
Should be fixed in #59. Sorry that it took a while.
