### ISSUE TITLE
Various comments regarding the template text

### ISSUE THREAD

**Issue by ghost** [contributoragreements/ca-cla-chooser#4]
These comments are based on the chooser's output when the following options are chosen:

Agreement Exclusivity	Non-Exclusive
Outbound License(s)	Not Applicable
Documentation License(s)	Not Applicable
Patents	Traditional Patent License

- [x] Section headings are inconsistently capitalized.
- [x] First use of "Individual" in the definition of "You" is capitalized, but Individual is not a defined term.
- [x] I would separate the obligation ("You have had Your employer...") from the definition, so that all obligations are clearly set out in the body of the agreement. Given the importance of that clause, I might consider putting it in the heading, before the definitions.
  - [x] Consider doing the same with "if you do not own the copyright..."
- [ ] "If you do not own the copyright..."
  - [ ] What about known patents?
  - [ ] "In the entire work of authorship" - might be more clear to say "in your Contribution"?
- [ ] "You" and "Contribution" speak of ownership, but "Copyright" speaks of ownership and control. Strongly suggest making those consistent.
- [x] "Copyright" speaks of "any extensions by You" - don't we care about all extensions, not just extensions by You?
- [ ] "Material": is it necessary to specify that "After you Submit... it may be included..."? Isn't that implied by Sec. 2? If it isn't implied by Sec. 2, would it be better to place it in Sec. 2 instead of this definition?
- [x] "Submit" is defined to include "to Us", so "to Us" in Submission Date is redundant.
- [x] Sec. 2.2 (Moral Rights) lacks a title, so inconsistent with the rest of Sec. 2. Ditto subsections of 7 and 8.
- [x] Sec. 2 is titled "License Grant" but Section 3 grants licenses. Should the titles be something like "2. Non-Patent License Grants" and "3. Patent License Grants"?
- [ ] Sec. 3.1: "Subject to the terms and conditions" appears to be redundant to "except as stated in Section 3.2"? I might say "Subject to revocation under Section 3.2, You hereby grant..." (removing the current parenthetical) or "You hereby grant..." (relying on the parenthetical).
- [x] Similarly, in Sec. 2.1, if there are conditions that could cause revocation of the copyright grant, it would be good to spell out what such conditions are.
- [ ] Sec. 4-6: Consider grouping these together into Section 4.1-4.3?
- [x] See also http://lu.is/blog/2012/08/19/a-quick-note-on-conspicuous-text-also-known-as-all-caps/
- [ ] 4: Consider, for readability and accuracy, giving this a more information title ("disclaimer of warranty") and reframing so that it applies to "you", e.g., WE ACKNOWLEDGE THAT YOU PROVIDE THE CONTRIBUTION "AS IS". MORE PARTICULARLY, YOU ... DISCLAIM... (This makes sense since We do not provide contributions.)
- [ ] 5: You or We, not You or Us?
- [ ] 7.1: Is there any jurisdiction where term does not begin at execution by default? i.e., is stating this explicitly necessary in some location?
- [ ] 7.2: Would it be easier/more clear to simply say that in case of termination, the only thing that is affected is the license for future Submissions? (This may be particularly important in the case of the non-exclusive/no outbound-license case, where the current language suggests that those licenses might terminate!)
- [x] 8.4: The Agreement is always going to be accurate; perhaps it would be better to say "Your representations under this Agreement"? (lower-case r representations, since there are no formal representations, but maybe this is an argument for bringing them back.)

**Comment by rejon** [comment]
This sounds like feedback for the CLA part of the agreement and not FLA.

**Comment by silverhook** [comment]
Have these been implemented already? A very quick scroll through the list makes me seem it does.

**Comment by mcjsca** [comment]
Reviewing both rendered preview under 4 and the PDF, checking what has been done ...

[individual-contributor-license-agreement-1.1-2019-04-16-20_45_53.pdf](https://github.com/contributoragreements/ca-cla-chooser/files/3086833/individual-contributor-license-agreement-1.1-2019-04-16-20_45_53.pdf)

**Comment by step21** [comment]
@silverhook @catharinamaracke these are all quite vague and relate to content. If I do not get any feedback that these need to be changed, to me it seems not necessary or a matter of opinion. Ofc, pull requests also welcome :)

**Comment by silverhook** [comment]
I’ll look into this this week.

**Comment by silverhook** [comment]
What remains would need to be considered as part of the next revision of the texts themselves. I will sync up with @catharinamaracke when we (in the forseable future) start working on the next version of the FLA and the CLA templates.

**Comment by silverhook** [comment]
Just discussed this on a call with @catharinamaracke and we’ll look into this in the 2021 revision of the text.

Let’s leave it open as a reminder for us.

**Comment by step21** [comment]
Ok

**Comment by silverhook** [comment]
Triaged. What’s actionable was moved to its separate issue.
