### ISSUE TITLE
PDF buttons lead to insecure URL

### ISSUE THREAD

**Issue by cornelius** [contributoragreements/ca-cla-chooser#42]
The PDF buttons on the last step of the wizard lead to http://fab2pdf.herokuapp.com/. This is rejected by browsers because it's an http URL. Should rather be a https URL.

**Comment by silverhook** [comment]
Good catch.

@step21, this should be simple to fix.

**Comment by silverhook** [comment]
Esp. should be fixed when #28 is fixed

**Comment by step21** [comment]
This should be fixed with in-browser pdf, it will not be fixed on Heroku, because that costs money. There is a WIP of the pdf feature under PRs, if you want it faster, please test this. Instructions for local testing are in the README.

**Comment by step21** [comment]
I'll close this, as the pdf feature is now disabled and if it comes back, it will be in-browser, thus removing any certificate issues.
