### ISSUE TITLE
Fix / introduce URL Shortener

### ISSUE THREAD

**Issue by silverhook** [contributoragreements/ca-cla-chooser#44]
According to the [README](https://github.com/contributoragreements/ca-cla-chooser#configuration) there should be a URL Shortener in use. But if there is one, it doesn’t seem to work.

This would be useful to have to send to people to (recreate and) read.

**Comment by step21** [comment]
Fixed on the sysadmin side. (https://github.com/contributoragreements/ca-cla-chooser/issues/74) Somehow, either when moving servers or at some other point the files became unreadable. This also means that old short urls no longer work, though it might have been like this for a long time, so maybe shouldn't affect too many. I'll probably write an e-mail to the hosters support to see if they can access these files.
