### ISSUE TITLE
Finalize implementation of FSFE FLA option

### ISSUE THREAD

**Issue by rejon** [contributoragreements/ca-cla-chooser#6]
from legal document

**Comment by rejon** [comment]
I have this one. It has comments in it.

**Comment by rejon** [comment]
Here are the steps to assess this:

- [ ] test out the current status of the code with the two paths FLA or CLA
- [ ] look at the code function
- [ ] make sure clear at all times that you are either doing FLA or CLA  options, probably show green or red at the top of the chooser once selected the path
- [ ] test from beginning to end the process and the final legal document generated

(Note, this is a beginning document...)

**Comment by danielriesner** [comment]
Please check if my solution resolves this issue: https://contributoragreements.github.io/ca-cla-chooser/

**Comment by silverhook** [comment]
This can be closed now

**Comment by mcjsca** [comment]
OK, closing
